# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skale < Formula
  desc "SkaleData CLI — manage clusters, apps, and deployments"
  homepage "https://skaledata.com"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skaledata/cli/releases/download/v0.1.0/skale_0.1.0_darwin_amd64.tar.gz"
      sha256 "42096397664a3cda47feb53900d79835d53da82eea82a98ae2e8ffc75e2e6986"

      define_method(:install) do
        bin.install "skale"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skaledata/cli/releases/download/v0.1.0/skale_0.1.0_darwin_arm64.tar.gz"
      sha256 "4987a7660f3010974f05c14cab35f292adebde056ea1ff7a97850ae3bb97a908"

      define_method(:install) do
        bin.install "skale"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skaledata/cli/releases/download/v0.1.0/skale_0.1.0_linux_amd64.tar.gz"
      sha256 "86ad1c84eafa19d982028f754fa56a0d84c34227c571f855e3b11e55a6ed00b1"
      define_method(:install) do
        bin.install "skale"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skaledata/cli/releases/download/v0.1.0/skale_0.1.0_linux_arm64.tar.gz"
      sha256 "437304eecf73c8f55ca25fa83c2d5f2d53b162b248d58a525e3f258f9a8578c4"
      define_method(:install) do
        bin.install "skale"
      end
    end
  end

  test do
    system "#{bin}/skale", "version"
  end
end
