# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skale < Formula
  desc "SkaleData CLI — manage clusters, apps, and deployments"
  homepage "https://skaledata.com"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skaledata/cli/releases/download/v0.1.4/skale_0.1.4_darwin_amd64.tar.gz"
      sha256 "08fabe83504d89481f87f06b984417eb90bb1a0857b4e3289f1964b43a255a6f"

      define_method(:install) do
        bin.install "skale"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skaledata/cli/releases/download/v0.1.4/skale_0.1.4_darwin_arm64.tar.gz"
      sha256 "d2ebaa25836146b36db73aeff992461bde07e9dead683e8699d14dd6b982e945"

      define_method(:install) do
        bin.install "skale"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skaledata/cli/releases/download/v0.1.4/skale_0.1.4_linux_amd64.tar.gz"
      sha256 "c5addd73b8edc31c126ae81f0160931aac434895e06d5f5c18b84aa75d591bf5"
      define_method(:install) do
        bin.install "skale"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skaledata/cli/releases/download/v0.1.4/skale_0.1.4_linux_arm64.tar.gz"
      sha256 "cfbe22546ad73ab508936cba854cf4b2debc02cbdb03e7180cf36871b21977dc"
      define_method(:install) do
        bin.install "skale"
      end
    end
  end

  test do
    system "#{bin}/skale", "version"
  end
end
