# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skale < Formula
  desc "SkaleData CLI — manage clusters, apps, and deployments"
  homepage "https://skaledata.com"
  version "0.1.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skaledata/cli/releases/download/v0.1.8/skale_0.1.8_darwin_amd64.tar.gz"
      sha256 "ffb11caa6584b9c501f6ef30073d3ec9ce55834e9e6adf7edfa171c24b5eab3b"

      define_method(:install) do
        bin.install "skale"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skaledata/cli/releases/download/v0.1.8/skale_0.1.8_darwin_arm64.tar.gz"
      sha256 "5bdac7d174b6bbfd2d40b220d45686a9f6d20f6f5d88eeb10fd20d5e2638b331"

      define_method(:install) do
        bin.install "skale"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skaledata/cli/releases/download/v0.1.8/skale_0.1.8_linux_amd64.tar.gz"
      sha256 "20bb687f8fed0aa067332a63263b29cb68ea6a13e2ce5af4a0f4bf9959422b72"
      define_method(:install) do
        bin.install "skale"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skaledata/cli/releases/download/v0.1.8/skale_0.1.8_linux_arm64.tar.gz"
      sha256 "ebbd039fa73b32a2830b3e5110375f9a4ea50b757f8f0199072a42c01f5c3868"
      define_method(:install) do
        bin.install "skale"
      end
    end
  end

  test do
    system "#{bin}/skale", "version"
  end
end
