# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skale < Formula
  desc "SkaleData CLI — manage clusters, apps, and deployments"
  homepage "https://skaledata.com"
  version "0.1.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skaledata/cli/releases/download/v0.1.10/skale_0.1.10_darwin_amd64.tar.gz"
      sha256 "788e3e5ecd8725efdf570297d0fede0a3efb72300788032dd01af90ab71046d2"

      define_method(:install) do
        bin.install "skale"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skaledata/cli/releases/download/v0.1.10/skale_0.1.10_darwin_arm64.tar.gz"
      sha256 "268683d46635f638f0a2b77bc798c43c7ddf2bd46390b6b774df98b58c5e020a"

      define_method(:install) do
        bin.install "skale"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skaledata/cli/releases/download/v0.1.10/skale_0.1.10_linux_amd64.tar.gz"
      sha256 "8f95cb89fd8ee23535154c72f9697feca8b04d3552746100bd2e8e10262b85a8"
      define_method(:install) do
        bin.install "skale"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skaledata/cli/releases/download/v0.1.10/skale_0.1.10_linux_arm64.tar.gz"
      sha256 "d4403ddeaa639c0ba0d65fd87864274b1e605a18203ff81c2b98324689e334e8"
      define_method(:install) do
        bin.install "skale"
      end
    end
  end

  test do
    system "#{bin}/skale", "version"
  end
end
